---
name: Build Images
on:
  push:
    branches:
      - 'gh-actions'

jobs:
  get_datetime:
    runs-on: ubuntu-latest
    outputs:
      datetime: ${{ steps.datetime.outputs.now }}

    steps:
      - id: datetime
        run: echo "::set-output name=now::$(date +%Y%m%d%H%M)"

  build:
    runs-on: ubuntu-latest
    needs: get_datetime

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: cop-java-builder:18.${{needs.get_datetime.outputs.datetime}}.0
          pull: true
