---
name: Build Images
on:
  push:
    branches:
      - 'gh-actions'

jobs:
  get_datetime:
    runs-on: ubuntu-latest
    outputs:
      datetime: ${{ steps.datetime.outputs.now }}

    steps:
      - id: datetime
        run: echo "::set-output name=now::$(date +%Y%m%d%H%M)"

  build:
    runs-on: ubuntu-latest
    needs: get_datetime
    strategy:
      matrix:
        java-version: ['18', '17']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Java Builder ${{ matrix.java-version }}
        uses: docker/build-push-action@v3
        with:
          build-args: JAVA_VERSION=${{ matrix.java-version }}
          context: .
          tags: cop-java-builder:${{ matrix.java-version }}.${{ needs.get_datetime.outputs.datetime }}.0
          pull: true
