---
name: Build Images
on:
  push:
    branches:
      - 'gh-actions'

env:
  IMAGE_NAME: cop-java-builder

jobs:
  get_datetime:
    runs-on: ubuntu-latest
    outputs:
      datetime: ${{ steps.datetime.outputs.now }}

    steps:
      - id: datetime
        run: echo "::set-output name=now::$(date +%Y%m%d%H%M)"

  build:
    runs-on: ubuntu-latest
    needs: get_datetime
    strategy:
      matrix:
        java-version: ['18', '17']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Java Builder ${{ matrix.java-version }} and export to Docker for test
        uses: docker/build-push-action@v3
        with:
          build-args: JAVA_VERSION=${{ matrix.java-version }}
          context: .
          load: true
          pull: true
          push: false
          tags: ${{ env.IMAGE_NAME }}:${{ matrix.java-version }}.test

      - name: Basic sanity check of image before push
        run: docker run --rm ${{ env.IMAGE_NAME }}:${{ matrix.java-version }}.test java --version

      - name: Test Happy
        run: echo "The test passed"
